apiVersion: v1
kind: Namespace
metadata:
  name: ebpf-monitor
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebpf-monitor
  namespace: ebpf-monitor
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ebpf-monitor-role
rules:
- nonResourceURLs:
    - "/version"
    - "/healthz"
  verbs: ["get"]
- apiGroups: ["batch"]
  resources:
    - "jobs"
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources:
    - "deployments"
    - "replicasets"
    - "ingresses"
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
    - "deployments"
    - "replicasets"
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
    - "namespaces"
    - "events"
    - "services"
    - "endpoints"
    - "nodes"
    - "pods"
    - "replicationcontrollers"
    - "componentstatuses"
    - "resourcequotas"
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
    - "endpoints"
  verbs: ["create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ebpf-monitor-role-binding
  namespace: ebpf-monitor
subjects:
- kind: ServiceAccount
  name: ebpf-monitor
  namespace: ebpf-monitor
roleRef:
  kind: ClusterRole
  name: ebpf-monitor-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ebpf-monitor
  labels:
    app: ebpf-monitor
  namespace: ebpf-monitor
spec:
  selector:
    matchLabels:
      name: ebpf-monitor
  template:
    metadata:
      name: ebpf-monitor
      labels:
        name: ebpf-monitor
      namespace: ebpf-monitor
    spec:
      serviceAccountName: ebpf-monitor
      hostIPC: true
      hostNetwork: true
      hostPID: true
      containers:
        - name: ebpf-monitor
          image: harbor.dds-sysu.tech/ebpf_monitor/ebpf_monitor:latest
          imagePullPolicy: Always
          env:
            - name: NODE_NAME #link: https://kubernetes.io/zh/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CONFIG
              value: /etc/config/config.yaml
          securityContext:
            privileged: true
          volumeMounts:
            - name: cfg-dir
              mountPath: /etc/config
            - name: kernel-modules
              mountPath: /lib/modules
              readOnly: true
            - name: boot
              mountPath: /boot
              readOnly: true
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: kernel-debug
              mountPath: /sys/kernel/debug
            - name: fs
              mountPath: /sys/fs
            - name: debug-root
              mountPath: /share
      volumes:
        - name: kernel-modules
          hostPath:
            path: /lib/modules
        - name: boot
          hostPath:
            path: /boot
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: kernel-debug
          hostPath: 
            path: /sys/kernel/debug
        - name: fs
          hostPath:
            path: /sys/fs
        - name: cfg-dir
          configMap:
            name: ebpf-config
        - name: debug-root
          hostPath:
            path: /root
